before_cache:
  - bundle clean
git:
  depth: 1
notifications:
  webhooks:
    - https://webhooks.gitter.im/e/3a11f6fb1385c5cdb12b
jobs:
  include:
    - stage: Deploy to RubyGems
      dist: xenial
      language: ruby
      rvm: 2.5.3
      env:
        - secure: WUn5OAyb8Y2F0myhs0ZEq5lg1yI7fvJVqFxSU/7BhoV7OTVNxJkUbCf0XNjgr8LQjAu/awVuLZfDncytbinqy/k8UOQqZpsdQXmHU+FsYnEVTcRGnI24NQzkPof3PI1cTjJAAXfYhoF04hGtNFxUHR3dMFXYJdIAfjsKxoxhTBqmjUF0eprRTy7F4YQuV3c8k3gf1ANJV4fzUspknp5Uy8IkKUbBKNgQ+WUJbE9RWRfxE3CbXmChJl1Z0Ozt3HDZ6UGIY04uGs/+W4gznnddX5vD5CdOZ5eDg0zdMgbzCyyHlZuwH3RW1qWk5ec0873/5CsUTJaLho5dwpqtgQg5dzkvr2xt3jsOWNduYnbtoSdSt+NN6khvLrrBInEUDhrmEU/OsIx0Eh8HHRVx1o44vPaFoXamBxuJc/gM16v46FuEGnvuDPImkrKx2TLIbLaatyYeSuOIO88yRjw5SEU+YpUpVCx6eBMXMF0JTNimH06qip+74GoCByc78ckYj3CC21HP8R8+6jahITrRR7Nv4pOHsSxBD/YBeSMJ/5jwAVFKY43DN0AGiH1NJGYZCJx72gdcGFfavHxjlQPbd04Sqy2WUPTkbeiAr39TJsPfHX+5feMrMLk0c+Yf9Slcf2tkItAn3nO7ZILR/W1BNUX3d7OlDHDlmf9XkvodKgRLCXk=
        - secure: BQD3quxFwkMat8deVbm4ynf1+7uG9xlVJoubCGjw26ZlcvclEC6bvBkkSKJBfnts599exjZI+03K3NC/zLj1l+frSVWtsuCN03oT1YtAiNqzodVpbOWGYhU3q67yN17KDa29AfglnVyCbB5PZAY1nt7ANJ0BWN5yDPiMky9EYRpzzh8dDixGJ7dG2T7JxvdsxZ5JRGTIk/MJQF4vcCar3ixxOUU9rv50jCk/pcHHNcHoIyiGTU4mue/YYTTfGuKtThIfheJGw5/1HnqYwKWCc3eHH0H0pN2H9p6lGLas1XqIg3Sv+98eoWNEQUjzgMdTFdbPSmi9NagxCCc9wuAKdZpdl8grTlO/2Rowd9orbGlPOhyQQ0thsqEhho0/YFxPPxU57T3pzXHm8N7+Qkyhwnko1M+ntu7e8ogVcV5s7S8Ro75ipTw9Jwn9R5k9EwGcSDggoNCScF0MbpsjH7cl54FtppitpsaMKQmVh215uPdrnhBU1epjg0dRhhuumiDQvSwqhWswFlZt/P4PZD6TM9nQpbyL94+m/+If2sn5le/IYssZRazw2qXsw/d3PNhx23BN4hLvOdRK2tHDtPSRBvC6n63SoQXeuXLbc0Ezkw3NWvN657CUJzOWvA2d1OKysggr9UlQ9CnF5ZHhy7zXy288q8fyQTO4fRwCpvwgexo=
      before_install:
        - gem install bundler --conservative --minimal-deps --no-document --version="~>
          2.0"
      install:
        - echo $rubygems_api_key_password | gpg --output ~/.gem/credentials --passphrase-fd
          0 rubygems/credentials.gpg
        - chmod 0600 ~/.gem/credentials
      script: true
      cache: false
      before_deploy:
        - echo $rubygems_private_key_password | gpg --output certs/gem-private_key.pem
          --passphrase-fd 0 certs/gem-private_key.pem.gpg
        - sha256sum certs/gem-private_key.pem | grep 7fd21648141c38cbfa08e3a7c16746c97811c750a0be727f737700fea0b4cebf
        - gem cert --add certs/gem-public_cert.pem
        - gem build kitchen-terraform.gemspec --silent
      deploy:
        provider: script
        script: gem push kitchen-terraform-*.gem
        gem: kitchen-terraform
        on:
          repo: newcontext-oss/kitchen-terraform
          tags: true
        skip_cleanup: true
